### ISSUE TITLE
Port to Webextensions

### ISSUE THREAD

**Issue by ainola** [djc/no-close-buttons#3]
We're nearing the end of being able to use this extension.

Thanks for this great extension!

**Comment by djc** [comment]
I know. As far as I know, the WebExtensions Theming API currently doesn't support inserting Chrome CSS. I'll aee about filing a bug for that if no one else has.

**Comment by roSievers** [comment]
I read the Mozilla bug you linked and am not really confident that they will manage to create an API in time for Firefox 57+. It would be great if the workaround suggested in the bug could be explained for users of your addon until Mozilla manages to provide some API. Feel free to copy and or modify my text.

# Workaround
Currently this addon doesn't work with Firefox 57+ due to limitations in the Firefox API. You have modify your personal `userChrome.css` file to remove close buttons, as suggested by Blake Winton. You can learn more about [userChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css) in the wiki, but you certainly don't have to.

## Find your profile directory
This should be a folder with a random name like `aaazqoic.default` located in your `firefox` directory. The name on your system will be different. On linux, this is `~/.mozilla/firefox/aaazqoic.default`. Refer to [the Mozilla wiki](http://kb.mozillazine.org/Profile_folder) if you are on a different system.

## Create the file
First, create a `chrome` folder inside the profile, then create `userChrome.css`. This should be located at `~/.mozilla/firefox/aaazqoic.default/chrome/userChrome.css` or your local equivalent.

## Paste the css content into the file
```css
/*
 * Do not remove the @namespace line -- it's required for correct functioning
 *  */
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul"); /* set default namespace to XUL */

.tab-close-button { display: none !important; }

```
